

import java.awt.GridLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dell
 */
public class HomeForm extends javax.swing.JFrame {

    private final dbConnection db;
    private String type;
    private int accountId;
    /**
     * Creates new form SingerForm
     */
    public HomeForm() {
        initComponents();
        setSize(500,650);
        this.type = "singer";
        
        db = new dbConnection();
        singerPanel.setSize(200,100);
        setPanel();
    }
    public HomeForm(int accountId) {
        initComponents();
        setSize(500,650);
        this.type = "singer";
        this.accountId = accountId;
        
        db = new dbConnection();
        singerPanel.setSize(200,100);
        setPanel();
    }
    public HomeForm(int accountId, String type) {
        initComponents();
        setSize(500,650);
        this.type = type;
        this.accountId = accountId;
        
        db = new dbConnection();
        
        setPanel();
    }
    
    public final void setPanel(){
        topLabel.setText(this.type);
        
        singerPanel.removeAll();
        singerPanel.setLayout(new GridLayout(0,1));
        ResultSet res;
        
        switch (this.type){
            case "singer" -> {
                res = db.selectQuery("select * from singer WHERE id_account="+this.accountId);
                try {
                    while(res.next()){
                        int id = res.getInt("id");
                        String name = res.getString("name");
                        int album_count = res.getInt("album_count");
                        byte[] photo = res.getBytes("photo");

                        singerPanel.add(new Singer(id, name, album_count, photo, this.accountId));
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(HomeForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            case "album" -> {
                res = db.selectQuery("select * from album WHERE id_account="+this.accountId);
                try {
                    while(res.next()){
                        int id = res.getInt("id");
                        int id_singer = res.getInt("id_singer");
                        String name = res.getString("name");
                        String label = res.getString("label");
                        byte[] photo = res.getBytes("photo");
                        
                        ResultSet res2 = db.selectQuery2("SELECT * FROM singer WHERE id="+id_singer+" AND id_account="+this.accountId);
                        if(res2.next()){
                            int singerId = res2.getInt("id");
                            String singerName = res2.getString("name");
                            int singerAlbum_count = res2.getInt("album_count");
                            byte[] singerPhoto = res2.getBytes("photo");
                            Singer singer = new Singer(singerId, singerName, singerAlbum_count, singerPhoto, this.accountId);
                            singerPanel.add(new Album(id, name, label, photo, singer,this.accountId));
                        }
                    }
                } catch (Exception ex) {
                    Logger.getLogger(HomeForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
        singerPanel.revalidate();
        singerPanel.repaint();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JScrollPane();
        singerPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        singerButton = new javax.swing.JButton();
        albumButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        topLabel.setFont(new java.awt.Font("Square721 BT", 0, 18)); // NOI18N
        topLabel.setText("Singers");
        getContentPane().add(topLabel);
        topLabel.setBounds(222, 33, 67, 23);

        javax.swing.GroupLayout singerPanelLayout = new javax.swing.GroupLayout(singerPanel);
        singerPanel.setLayout(singerPanelLayout);
        singerPanelLayout.setHorizontalGroup(
            singerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );
        singerPanelLayout.setVerticalGroup(
            singerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );

        jPanel1.setViewportView(singerPanel);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(49, 135, 412, 371);

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton);
        addButton.setBounds(389, 94, 72, 23);

        singerButton.setText("Singer");
        singerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                singerButtonMouseClicked(evt);
            }
        });
        getContentPane().add(singerButton);
        singerButton.setBounds(49, 94, 72, 23);

        albumButton.setText("Album");
        albumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albumButtonActionPerformed(evt);
            }
        });
        getContentPane().add(albumButton);
        albumButton.setBounds(222, 94, 72, 23);

        logOutButton.setText("Log out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logOutButton);
        logOutButton.setBounds(19, 23, 72, 23);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 500, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        switch (this.type){
            case "singer" -> {
                AddSingerForm addSingerForm = new AddSingerForm(this.accountId);
                addSingerForm.setVisible(true);
            }
            case "album" -> {
                AddAlbumForm addAlbumForm = new AddAlbumForm(this.accountId);
                addAlbumForm.setVisible(true);
            }
        }
        this.dispose();
    }//GEN-LAST:event_addButtonActionPerformed

    private void albumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albumButtonActionPerformed
        // TODO add your handling code here:
        if(!this.type.equals("album")){
            this.type = "album";
            setPanel();
        }
    }//GEN-LAST:event_albumButtonActionPerformed

    private void singerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_singerButtonMouseClicked
        // TODO add your handling code here:
        if(!this.type.equals("singer")){
            this.type = "singer";
            setPanel();
        }
    }//GEN-LAST:event_singerButtonMouseClicked

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // TODO add your handling code here:
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logOutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton albumButton;
    private javax.swing.JScrollPane jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton singerButton;
    private javax.swing.JPanel singerPanel;
    private javax.swing.JLabel topLabel;
    // End of variables declaration//GEN-END:variables
}
