
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Dell
 */
public class Singer extends javax.swing.JPanel {

    private int id;
    private String name;
    private int album_count;
    private byte[] photo;
    private dbConnection db;
    private int accountId;
    /**
     * Creates new form Singer
     */
    public Singer() {
        initComponents();
        setSize(500,650);
        db = new dbConnection();
    }
    public Singer(int accountId) {
        this();
        this.accountId = accountId;
    }
    public Singer(int id, String name, int album_count, byte[] photo, int accountId) {
        this(accountId);
        this.id = id;
        this.name = name;
        this.album_count = album_count;
        this.photo = photo;
        
        nameLabel.setText(name);
        albumLabel.setText(Integer.toString(album_count));
        
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(photo).getImage().getScaledInstance(125,89,Image.SCALE_SMOOTH));
        imageLabel.setIcon(imageIcon);
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public int getAlbum_count() {
        return album_count;
    }

    public byte[] getPhoto() {
        return photo;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
    
    public void deleteData(){
        String sql = "DELETE FROM album WHERE id_singer ="+id;
        db.updateQuery(sql);
        
        sql = "DELETE FROM singer WHERE `id` = "+id+"";
        db.updateQuery(sql);
        
        HomeForm mainFrame = (HomeForm) this.getTopLevelAncestor();
        mainFrame.setPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        albumLabel = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(354, 101));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(null);

        jLabel1.setText("Name:");
        add(jLabel1);
        jLabel1.setBounds(150, 19, 35, 16);

        nameLabel.setText("name");
        add(nameLabel);
        nameLabel.setBounds(196, 19, 70, 16);

        jLabel2.setText("Album");
        add(jLabel2);
        jLabel2.setBounds(149, 45, 36, 16);

        albumLabel.setText("album");
        add(albumLabel);
        albumLabel.setBounds(196, 45, 34, 16);
        add(imageLabel);
        imageLabel.setBounds(6, 6, 125, 89);

        editButton.setText("edit");
        editButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editButtonMouseClicked(evt);
            }
        });
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        add(editButton);
        editButton.setBounds(276, 16, 72, 23);

        deleteButton.setText("delete");
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });
        add(deleteButton);
        deleteButton.setBounds(276, 45, 72, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonActionPerformed

    private void editButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseClicked
        // TODO add your handling code here:
        AddSingerForm addSingerForm = new AddSingerForm(this.accountId,this);
        addSingerForm.setVisible(true);
        
        HomeForm homeForm = (HomeForm) getTopLevelAncestor();
        homeForm.dispose();
    }//GEN-LAST:event_editButtonMouseClicked

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "delete?","confirm",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            
        switch (response) {
            case JOptionPane.YES_OPTION:
                deleteData();
                break;
            case JOptionPane.NO_OPTION:
                System.out.println("canceled");
                break;
            case JOptionPane.CLOSED_OPTION:
                System.out.println("closed");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_deleteButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel albumLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
